import '@/globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Container from '@/components/container'
import Footer from '@/components/footer/footer'
import Header from '@/components/header'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { i18n, type Locale } from '@/i18n-config'

const inter = Inter({ subsets: ['latin'] })

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: Locale }
}>) {
  return (
    // suppressHydrationWarning -> https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
    <html lang={params.lang} suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Header lang={params.lang} />
          <main className="py-28">
            <Container>{children}</Container>
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
